default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DATABASE_USER", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  socket: <%= ENV.fetch("DATABASE_SOCKET", "/tmp/mysql.sock") %>

development:
  <<: *default
  database: gibbon_development

test:
  <<: *default
  database: gibbon_test

staging:
  <<: *default
  database: gibbon_staging

production:
  <<: *default
  database: gibbon_production
